<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>1.0.6</Version>
    <AssemblyVersion>1.0.6.0</AssemblyVersion>
    <FileVersion>1.0.6.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PdfSharp" Version="6.2.4" />
    <PackageReference Include="System.Data.Odbc" Version="10.0.10" />
  </ItemGroup>

</Project>